### ISSUE TITLE
Consider removing Dota 2 support

### ISSUE THREAD

**Issue by asheroto** [seDirector/App#76]
DAYBR3AK will comment after me

**Comment by DAYBR3AK1999** [comment]
Dota 2 dedicated server creation for Windows is currently unsupported due to the change from Source 1 to Source 2.
To make Dota 2 dedicated server on Windows and be able to join it you will need MetaMod to be loaded to be able to load other dota maps after a game has finished, which as for now isn't supported anymore.
The only way to be able to create a Dota 2 dedicated server would be under Linux and adding MetaMod while you will also need to modify Game.inf file to redirect where the path to MetaMod's bin file is and you will need to rename a certain Linux64 folder to steamrt64.
Dota 2 implemented a system where players can host their custom game directly in-game, but as it says itself, you need to be in-game which means you can't play anything else or let the server run in the background.
I asked here and there if there are some workarounds for Dota 2 server creation on Windows with currently no answers.
As for now it is better to disable Dota 2 Windows server creation, until more info about a workaround and be able to join your server is possible.

**Comment by asheroto** [comment]
So just to confirm, you can only run and create Dota 2 on Linux?

There's no way to do it without a hacky/workaround with MetaMod?

No official way, right?

**Comment by asheroto** [comment]
Removed in version `7.4.4`.
